name: Lint, Build and Test Lilo
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
jobs:
  lint-build-and-test:
    name: 'lint, build and test lilo'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Prettier check
        run: pnpm prettier-lilo

      - name: Linting
        run: pnpm lint-lilo

      - name: Build Lilo
        run: pnpm build-lilo

      - name: Build Tests
        run: pnpm test-lilo

      - name: Run Tests
        uses: lunarmodules/busted@v2.1.2
        with:
          args: packages/lilo/tests_out --pattern="%.test%." --lpath="packages/lilo/tests_out/?.lua"
